spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yulian@123
    url: jdbc:mysql://101.66.244.52:33306/mall?characterEncoding=utf-8&useSSL=false
  redis:
    host: 81.68.99.26
    port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml

server:
  servlet:
    session:
      timeout: 1800
